version: '3'
services:
    
    app:  
        build: .
        ports:
            - 13000:13000
        command: [sh, -c, npm run dev]
        volumes:
            - ".:/app"
            - "/app/node_modules"
            - "/app/.nuxt"
        stdin_open: true
        tty: true
